# Generated by Django 3.2.11 on 2022-01-11 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(blank=True, default=0, null=True, verbose_name='количество шагов')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='время')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователя',
            },
        ),
    ]
