# Generated by Django 3.2.11 on 2022-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='имя'),
        ),
    ]
